"""GplearnEngine — gplearn-based implementation of IGeneticEngine.

Uses gplearn's SymbolicRegressor for symbolic regression on scheduling
decision data, producing interpretable expression trees comparable to
DEAP-evolved rules.

Unlike DEAP (simulation-based fitness), this engine trains on labeled
scheduling data generated by running a reference strategy on the
training instances.  The terminal features for each (pod, node) pair
are the X inputs, and the target y is a reference quality score.

This creates a meaningful comparison for the dissertation:
  - DEAP: **online** learning — rules optimised directly via simulation
  - gplearn: **offline** learning — rules learned from reference schedules
"""

from __future__ import annotations

import logging
from typing import Any, Callable, Dict, List, Optional

import numpy as np
from gplearn.functions import make_function
from gplearn.genetic import SymbolicRegressor

from config.schema import ClusterConfig, DynamicsConfig
from gp.interface import GPResult, IGeneticEngine
from gp.primitives import FUNCTION_SET, TERMINAL_NAMES, extract_terminal_values
from models.cluster_state import ClusterState
from models.node import Node
from models.pod import Pod
from scheduling.balanced_allocation import BalancedAllocationStrategy
from scheduling.least_allocated import LeastAllocatedStrategy
from scheduling.most_allocated import MostAllocatedStrategy
from scheduling.strategy import ISchedulingStrategy
from simulator.engine import SimulationEngine

logger = logging.getLogger(__name__)


# ── Custom gplearn functions ─────────────────────────────────────────────

def _if_positive_vec(x1: np.ndarray, x2: np.ndarray, x3: np.ndarray) -> np.ndarray:
    """Vectorised if_positive: x2 where x1 > 0, else x3."""
    return np.where(x1 > 0, x2, x3)


_gplearn_if_positive = make_function(
    function=_if_positive_vec,
    name="if_positive",
    arity=3,
)


# ── Data-collection strategy ────────────────────────────────────────────

class _ScoringCollector(ISchedulingStrategy):
    """Wraps a reference strategy and records terminal features at each decision.

    Used internally by :class:`GplearnEngine` to generate labelled
    training data for symbolic regression.
    """

    def __init__(self, inner: ISchedulingStrategy) -> None:
        self._inner = inner
        self._current_time: float = 0.0
        self.records: List[tuple] = []  # list of (features_dict, score)

    @property
    def name(self) -> str:
        return f"Collector({self._inner.name})"

    def set_current_time(self, t: float) -> None:
        self._current_time = t
        if hasattr(self._inner, "set_current_time"):
            self._inner.set_current_time(t)

    def select_node(self, pod: Pod, cluster: ClusterState) -> Optional[str]:
        chosen = self._inner.select_node(pod, cluster)

        # Record features and reference score for every feasible node
        for node in cluster.feasible_nodes(pod):
            features = extract_terminal_values(
                pod, node, cluster, self._current_time
            )
            # Reference quality: resource availability ratio (LeastAllocated)
            score = (
                node.cpu_available / max(node.cpu_capacity, 1e-9)
                + node.mem_available / max(node.mem_capacity, 1e-9)
            ) / 2.0
            self.records.append((features, score))

        return chosen

    def on_episode_start(self, cluster: ClusterState) -> None:
        self._inner.on_episode_start(cluster)

    def on_episode_end(self, cluster: ClusterState) -> None:
        self._inner.on_episode_end(cluster)


# ── Engine implementation ────────────────────────────────────────────────

class GplearnEngine(IGeneticEngine):
    """GP engine backed by gplearn's :class:`SymbolicRegressor`.

    Lifecycle:
      1. ``setup(terminal_names, training_instances=..., cluster_config=..., ...)``
      2. ``train(fitness_function, seed)``
      3. ``evaluate_individual(program, terminal_values)``
    """

    def __init__(self) -> None:
        self._terminal_names: List[str] = []
        self._function_names: List[str] = []
        self._params: Dict[str, Any] = {}
        self._setup_done = False
        self._model: Optional[SymbolicRegressor] = None

        # Data needed for training-data generation (set in setup)
        self._training_instances: List[List[Pod]] = []
        self._cluster_config: Optional[ClusterConfig] = None
        self._dynamics_config: Optional[DynamicsConfig] = None
        self._reference_strategies: List[type] = [LeastAllocatedStrategy]

    # ── IGeneticEngine interface ─────────────────────────────────────

    @property
    def name(self) -> str:
        return "gplearn"

    def setup(
        self,
        terminal_names: Optional[List[str]] = None,
        function_set: Optional[List[str]] = None,
        **kwargs: Any,
    ) -> None:
        """Configure the gplearn engine.

        In addition to standard GP parameters, accepts engine-specific
        keyword arguments:

            training_instances:  ``List[List[Pod]]`` used to generate
                                 regression training data.
            cluster_config:      ``ClusterConfig`` used to build the
                                 simulation cluster.
            dynamics_config:     ``DynamicsConfig`` (optional) for node
                                 failure injection during data-generation
                                 simulations.
        """
        self._terminal_names = terminal_names or list(TERMINAL_NAMES)
        self._function_names = function_set or list(FUNCTION_SET.keys())

        self._params = {
            "population_size": kwargs.get("population_size", 150),
            "n_generations": kwargs.get("n_generations", 50),
            "tournament_size": kwargs.get("tournament_size", 3),
            "crossover_prob": kwargs.get("crossover_prob", 0.8),
            "mutation_prob": kwargs.get("mutation_prob", 0.2),
            "max_tree_depth": kwargs.get("max_tree_depth", 10),
            "parsimony_coefficient": kwargs.get("parsimony_coefficient", 0.001),
        }

        # Engine-specific: data sources for regression training
        self._training_instances = kwargs.get("training_instances", [])
        self._cluster_config = kwargs.get("cluster_config", None)
        self._dynamics_config = kwargs.get("dynamics_config", None)

        # Multiple reference strategies for richer training data
        ref = kwargs.get("reference_strategies", None)
        if ref:
            self._reference_strategies = list(ref)
        else:
            single = kwargs.get("reference_strategy", LeastAllocatedStrategy)
            self._reference_strategies = [single]

        self._setup_done = True

    def train(
        self,
        fitness_function: Callable[..., float],
        seed: int = 42,
    ) -> GPResult:
        """Train via symbolic regression on simulated scheduling data.

        1. Generate labelled (X, y) data by running a reference strategy
           on training instances and collecting terminal features.
        2. Fit a ``SymbolicRegressor`` on that data.
        3. Return the best program as a ``GPResult``.
        """
        if not self._setup_done:
            raise RuntimeError("Call setup() before train().")

        # Generate training data
        X, y = self._generate_training_data(seed)
        logger.info(
            "Generated %d training samples (%d features) for gplearn",
            len(X), X.shape[1] if len(X) > 0 else 0,
        )

        if len(X) == 0:
            raise RuntimeError(
                "No training data generated — check training_instances and cluster_config"
            )

        # Build gplearn function set
        func_set = self._build_function_set()

        # Map GP parameters to gplearn parameters
        mut = self._params["mutation_prob"]
        max_d = self._params["max_tree_depth"]

        model = SymbolicRegressor(
            population_size=self._params["population_size"],
            generations=self._params["n_generations"],
            tournament_size=self._params["tournament_size"],
            p_crossover=self._params["crossover_prob"],
            p_subtree_mutation=mut * 0.5,
            p_hoist_mutation=mut * 0.1,
            p_point_mutation=mut * 0.3,
            p_point_replace=mut * 0.1,
            init_depth=(2, min(6, max_d)),
            function_set=func_set,
            metric="mean absolute error",
            parsimony_coefficient=self._params["parsimony_coefficient"],
            const_range=(-5.0, 5.0),
            feature_names=self._terminal_names,
            random_state=seed,
            verbose=0,
            n_jobs=1,
        )

        model.fit(X, y)
        self._model = model

        best_program = model._program
        log_data = self._extract_log(model)

        return GPResult(
            best_individual=best_program,
            best_fitness=best_program.raw_fitness_,
            best_expression=str(best_program),
            generations=self._params["n_generations"],
            log=log_data,
            hall_of_fame=[best_program],
        )

    def evaluate_individual(
        self,
        individual: Any,
        terminal_values: Dict[str, float],
    ) -> float:
        """Evaluate a gplearn program on concrete terminal values."""
        row = np.array(
            [[terminal_values[name] for name in self._terminal_names]],
            dtype=np.float64,
        )
        try:
            result = individual.execute(row)
            val = float(result[0])
            if not np.isfinite(val):
                return 0.0
            return val
        except (OverflowError, ZeroDivisionError, ValueError):
            return 0.0

    def get_expression_string(self, individual: Any) -> str:
        return str(individual)

    # ── Internal helpers ─────────────────────────────────────────────

    def _build_function_set(self) -> tuple:
        """Map project function names to gplearn-compatible objects."""
        mapping: dict[str, Any] = {
            "add": "add",
            "sub": "sub",
            "mul": "mul",
            "protected_div": "div",     # gplearn's div is already protected
            "neg": "neg",
            "min": "min",
            "max": "max",
            "if_positive": _gplearn_if_positive,
        }
        funcs = []
        for name in self._function_names:
            if name in mapping:
                funcs.append(mapping[name])
        return tuple(funcs) if funcs else ("add", "sub", "mul", "div")

    def _generate_training_data(
        self,
        seed: int,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Generate (X, y) from reference-strategy simulations.

        Runs ``LeastAllocatedStrategy`` on each training instance and
        records terminal features at every scheduling decision.
        The target *y* is the resource-availability ratio (the metric
        LeastAllocated optimises), giving gplearn meaningful regression
        targets to learn from.
        """
        all_X: List[List[float]] = []
        all_y: List[float] = []

        for strategy_cls in self._reference_strategies:
            for idx, instance_pods in enumerate(self._training_instances):
                inner_strategy = strategy_cls()
                collector_strategy = _ScoringCollector(inner_strategy)

                fresh_pods = [_copy_pod(p) for p in instance_pods]
                failure_seed = seed + idx * 7919

                engine = SimulationEngine(
                    strategy=collector_strategy,
                    cluster_config=self._cluster_config,
                    dynamics_config=self._dynamics_config,
                    failure_seed=failure_seed,
                )
                engine.build_cluster()
                engine.load_workload(fresh_pods)
                engine.run()

                for features_dict, score in collector_strategy.records:
                    row = [features_dict[name] for name in self._terminal_names]
                    all_X.append(row)
                    all_y.append(score)

        if not all_X:
            return np.empty((0, len(self._terminal_names))), np.empty(0)

        return np.array(all_X, dtype=np.float64), np.array(all_y, dtype=np.float64)

    @staticmethod
    def _extract_log(model: SymbolicRegressor) -> List[Dict[str, Any]]:
        """Convert gplearn's ``run_details_`` to our log format."""
        log = []
        details = model.run_details_
        n_gens = len(details.get("generation", []))
        for i in range(n_gens):
            entry: Dict[str, Any] = {
                "gen": details["generation"][i],
                "nevals": details["generation"][i],  # gplearn doesn't track nevals
                "min": details["best_fitness"][i],
                "avg": details["average_fitness"][i],
                "std": 0.0,  # not tracked by gplearn
            }
            log.append(entry)
        return log


# ── Module-level helpers ────────────────────────────────────────────────

def _copy_pod(pod: Pod) -> Pod:
    """Create a fresh copy of a pod (reset mutable state)."""
    return Pod(
        pod_id=pod.pod_id,
        cpu_request=pod.cpu_request,
        mem_request=pod.mem_request,
        gpu_request=pod.gpu_request,
        priority=pod.priority,
        qos_class=pod.qos_class,
        arrival_time=pod.arrival_time,
        duration=pod.duration,
        namespace=pod.namespace,
        tolerations=pod.tolerations,
        node_selector=pod.node_selector,
        cpu_limit=pod.cpu_limit,
        mem_limit=pod.mem_limit,
        anti_affinity_key=pod.anti_affinity_key,
        workload_type=pod.workload_type,
        replica_group=pod.replica_group,
    )
